apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: helm
    repoURL: https://github.com/lindblad/devops-toolkit.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: vfarcic/devops-toolkit
          tag: {{.IMAGE_TAG}}
        ingress:
          host: staging.devopstoolkitseries.20.86.207.9.sslip.io
      version: v3
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

